/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/org/$slug'
import { Route as unauthenticatedRegisterRouteImport } from './routes/(unauthenticated)/register'
import { Route as unauthenticatedLoginRouteImport } from './routes/(unauthenticated)/login'
import { Route as authenticatedJoinOrganizationRouteImport } from './routes/(authenticated)/join-organization'
import { Route as authenticatedCreateOrganizationRouteImport } from './routes/(authenticated)/create-organization'
import { Route as OrgSlugunauthenticatedRouteRouteImport } from './routes/org/$slug/(unauthenticated)/route'
import { Route as OrgSlugauthenticatedRouteRouteImport } from './routes/org/$slug/(authenticated)/route'
import { Route as OrgSlugauthenticatedIndexRouteImport } from './routes/org/$slug/(authenticated)/index'
import { Route as OrgSlugunauthenticatedRegisterRouteImport } from './routes/org/$slug/(unauthenticated)/register'
import { Route as OrgSlugunauthenticatedLoginRouteImport } from './routes/org/$slug/(unauthenticated)/login'
import { Route as OrgSlugauthenticatedOnboardingRouteImport } from './routes/org/$slug/(authenticated)/onboarding'
import { Route as OrgSlugauthenticatedSettingsRouteRouteImport } from './routes/org/$slug/(authenticated)/settings/route'
import { Route as OrgSlugauthenticatedPortalRouteRouteImport } from './routes/org/$slug/(authenticated)/portal/route'
import { Route as OrgSlugauthenticatedAdminRouteRouteImport } from './routes/org/$slug/(authenticated)/admin/route'
import { Route as OrgSlugauthenticatedSettingsIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/index'
import { Route as OrgSlugauthenticatedPortalIndexRouteImport } from './routes/org/$slug/(authenticated)/portal/index'
import { Route as OrgSlugauthenticatedAdminIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/index'
import { Route as OrgSlugauthenticatedPortalFeedRouteImport } from './routes/org/$slug/(authenticated)/portal/feed'
import { Route as OrgSlugauthenticatedAdminFeedRouteImport } from './routes/org/$slug/(authenticated)/admin/feed'
import { Route as OrgSlugauthenticatedPortalCalendarIndexRouteImport } from './routes/org/$slug/(authenticated)/portal/calendar/index'
import { Route as OrgSlugauthenticatedAdminServicesIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/services/index'
import { Route as OrgSlugauthenticatedAdminMembersIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/members/index'
import { Route as OrgSlugauthenticatedAdminLessonsIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/lessons/index'
import { Route as OrgSlugauthenticatedAdminCalendarIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/calendar/index'
import { Route as OrgSlugauthenticatedAdminBoardsIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/boards/index'
import { Route as OrgSlugauthenticatedSettingsOrganizationBusinessHoursRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/business-hours'
import { Route as OrgSlugauthenticatedSettingsAccountGuardianRouteImport } from './routes/org/$slug/(authenticated)/settings/account/guardian'
import { Route as OrgSlugauthenticatedSettingsAccountAvailabilityRouteImport } from './routes/org/$slug/(authenticated)/settings/account/availability'
import { Route as OrgSlugauthenticatedAdminServicesNewRouteImport } from './routes/org/$slug/(authenticated)/admin/services/new'
import { Route as OrgSlugauthenticatedAdminLessonsNewRouteImport } from './routes/org/$slug/(authenticated)/admin/lessons/new'
import { Route as OrgSlugauthenticatedAdminCalendarNewRouteImport } from './routes/org/$slug/(authenticated)/admin/calendar/new'
import { Route as OrgSlugauthenticatedAdminBoardsNewRouteImport } from './routes/org/$slug/(authenticated)/admin/boards/new'
import { Route as OrgSlugauthenticatedSettingsOrganizationWaiversIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/waivers/index'
import { Route as OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/questionnaires/index'
import { Route as OrgSlugauthenticatedSettingsOrganizationMembersIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/members/index'
import { Route as OrgSlugauthenticatedSettingsOrganizationGeneralIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/general/index'
import { Route as OrgSlugauthenticatedSettingsAccountSecurityIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/account/security/index'
import { Route as OrgSlugauthenticatedSettingsAccountProfileIndexRouteImport } from './routes/org/$slug/(authenticated)/settings/account/profile/index'
import { Route as OrgSlugauthenticatedAdminServicesIdIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/services/$id.index'
import { Route as OrgSlugauthenticatedAdminMembersTrainersIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/members/trainers/index'
import { Route as OrgSlugauthenticatedAdminMembersRidersIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/members/riders/index'
import { Route as OrgSlugauthenticatedAdminMembersIdIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/members/$id.index'
import { Route as OrgSlugauthenticatedAdminBoardsIdIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/boards/$id.index'
import { Route as OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/questionnaires/new'
import { Route as OrgSlugauthenticatedAdminServicesIdEditRouteImport } from './routes/org/$slug/(authenticated)/admin/services/$id.edit'
import { Route as OrgSlugauthenticatedAdminMembersTrainersTrainerIdRouteImport } from './routes/org/$slug/(authenticated)/admin/members/trainers/$trainerId'
import { Route as OrgSlugauthenticatedAdminMembersRidersRiderIdRouteImport } from './routes/org/$slug/(authenticated)/admin/members/riders/$riderId'
import { Route as OrgSlugauthenticatedAdminBoardsIdEditRouteImport } from './routes/org/$slug/(authenticated)/admin/boards/$id.edit'
import { Route as OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRouteImport } from './routes/org/$slug/(authenticated)/admin/members/riders/$riderId.index'
import { Route as OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRouteImport } from './routes/org/$slug/(authenticated)/settings/organization/questionnaires/$id.edit'
import { Route as OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRouteImport } from './routes/org/$slug/(authenticated)/admin/members/riders/$riderId.activity'

const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthenticatedRegisterRoute = unauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const unauthenticatedLoginRoute = unauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => unauthenticatedRouteRoute,
} as any)
const authenticatedJoinOrganizationRoute =
  authenticatedJoinOrganizationRouteImport.update({
    id: '/join-organization',
    path: '/join-organization',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedCreateOrganizationRoute =
  authenticatedCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const OrgSlugunauthenticatedRouteRoute =
  OrgSlugunauthenticatedRouteRouteImport.update({
    id: '/(unauthenticated)',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugauthenticatedRouteRoute =
  OrgSlugauthenticatedRouteRouteImport.update({
    id: '/(authenticated)',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugauthenticatedIndexRoute =
  OrgSlugauthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugauthenticatedRouteRoute,
  } as any)
const OrgSlugunauthenticatedRegisterRoute =
  OrgSlugunauthenticatedRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => OrgSlugunauthenticatedRouteRoute,
  } as any)
const OrgSlugunauthenticatedLoginRoute =
  OrgSlugunauthenticatedLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => OrgSlugunauthenticatedRouteRoute,
  } as any)
const OrgSlugauthenticatedOnboardingRoute =
  OrgSlugauthenticatedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => OrgSlugauthenticatedRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsRouteRoute =
  OrgSlugauthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgSlugauthenticatedRouteRoute,
  } as any)
const OrgSlugauthenticatedPortalRouteRoute =
  OrgSlugauthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => OrgSlugauthenticatedRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminRouteRoute =
  OrgSlugauthenticatedAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => OrgSlugauthenticatedRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsIndexRoute =
  OrgSlugauthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedPortalIndexRoute =
  OrgSlugauthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugauthenticatedPortalRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminIndexRoute =
  OrgSlugauthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedPortalFeedRoute =
  OrgSlugauthenticatedPortalFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => OrgSlugauthenticatedPortalRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminFeedRoute =
  OrgSlugauthenticatedAdminFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedPortalCalendarIndexRoute =
  OrgSlugauthenticatedPortalCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => OrgSlugauthenticatedPortalRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminServicesIndexRoute =
  OrgSlugauthenticatedAdminServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersIndexRoute =
  OrgSlugauthenticatedAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminLessonsIndexRoute =
  OrgSlugauthenticatedAdminLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminCalendarIndexRoute =
  OrgSlugauthenticatedAdminCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminBoardsIndexRoute =
  OrgSlugauthenticatedAdminBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute =
  OrgSlugauthenticatedSettingsOrganizationBusinessHoursRouteImport.update({
    id: '/organization/business-hours',
    path: '/organization/business-hours',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsAccountGuardianRoute =
  OrgSlugauthenticatedSettingsAccountGuardianRouteImport.update({
    id: '/account/guardian',
    path: '/account/guardian',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsAccountAvailabilityRoute =
  OrgSlugauthenticatedSettingsAccountAvailabilityRouteImport.update({
    id: '/account/availability',
    path: '/account/availability',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminServicesNewRoute =
  OrgSlugauthenticatedAdminServicesNewRouteImport.update({
    id: '/services/new',
    path: '/services/new',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminLessonsNewRoute =
  OrgSlugauthenticatedAdminLessonsNewRouteImport.update({
    id: '/lessons/new',
    path: '/lessons/new',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminCalendarNewRoute =
  OrgSlugauthenticatedAdminCalendarNewRouteImport.update({
    id: '/calendar/new',
    path: '/calendar/new',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminBoardsNewRoute =
  OrgSlugauthenticatedAdminBoardsNewRouteImport.update({
    id: '/boards/new',
    path: '/boards/new',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute =
  OrgSlugauthenticatedSettingsOrganizationWaiversIndexRouteImport.update({
    id: '/organization/waivers/',
    path: '/organization/waivers/',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute =
  OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRouteImport.update(
    {
      id: '/organization/questionnaires/',
      path: '/organization/questionnaires/',
      getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
    } as any,
  )
const OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute =
  OrgSlugauthenticatedSettingsOrganizationMembersIndexRouteImport.update({
    id: '/organization/members/',
    path: '/organization/members/',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute =
  OrgSlugauthenticatedSettingsOrganizationGeneralIndexRouteImport.update({
    id: '/organization/general/',
    path: '/organization/general/',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsAccountSecurityIndexRoute =
  OrgSlugauthenticatedSettingsAccountSecurityIndexRouteImport.update({
    id: '/account/security/',
    path: '/account/security/',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsAccountProfileIndexRoute =
  OrgSlugauthenticatedSettingsAccountProfileIndexRouteImport.update({
    id: '/account/profile/',
    path: '/account/profile/',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminServicesIdIndexRoute =
  OrgSlugauthenticatedAdminServicesIdIndexRouteImport.update({
    id: '/services/$id/',
    path: '/services/$id/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersTrainersIndexRoute =
  OrgSlugauthenticatedAdminMembersTrainersIndexRouteImport.update({
    id: '/members/trainers/',
    path: '/members/trainers/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersRidersIndexRoute =
  OrgSlugauthenticatedAdminMembersRidersIndexRouteImport.update({
    id: '/members/riders/',
    path: '/members/riders/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersIdIndexRoute =
  OrgSlugauthenticatedAdminMembersIdIndexRouteImport.update({
    id: '/members/$id/',
    path: '/members/$id/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminBoardsIdIndexRoute =
  OrgSlugauthenticatedAdminBoardsIdIndexRouteImport.update({
    id: '/boards/$id/',
    path: '/boards/$id/',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute =
  OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRouteImport.update({
    id: '/organization/questionnaires/new',
    path: '/organization/questionnaires/new',
    getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminServicesIdEditRoute =
  OrgSlugauthenticatedAdminServicesIdEditRouteImport.update({
    id: '/services/$id/edit',
    path: '/services/$id/edit',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute =
  OrgSlugauthenticatedAdminMembersTrainersTrainerIdRouteImport.update({
    id: '/members/trainers/$trainerId',
    path: '/members/trainers/$trainerId',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersRidersRiderIdRoute =
  OrgSlugauthenticatedAdminMembersRidersRiderIdRouteImport.update({
    id: '/members/riders/$riderId',
    path: '/members/riders/$riderId',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminBoardsIdEditRoute =
  OrgSlugauthenticatedAdminBoardsIdEditRouteImport.update({
    id: '/boards/$id/edit',
    path: '/boards/$id/edit',
    getParentRoute: () => OrgSlugauthenticatedAdminRouteRoute,
  } as any)
const OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute =
  OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugauthenticatedAdminMembersRidersRiderIdRoute,
  } as any)
const OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute =
  OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRouteImport.update(
    {
      id: '/organization/questionnaires/$id/edit',
      path: '/organization/questionnaires/$id/edit',
      getParentRoute: () => OrgSlugauthenticatedSettingsRouteRoute,
    } as any,
  )
const OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute =
  OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => OrgSlugauthenticatedAdminMembersRidersRiderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organization': typeof authenticatedCreateOrganizationRoute
  '/join-organization': typeof authenticatedJoinOrganizationRoute
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/org/$slug': typeof OrgSlugunauthenticatedRouteRouteWithChildren
  '/org/$slug/admin': typeof OrgSlugauthenticatedAdminRouteRouteWithChildren
  '/org/$slug/portal': typeof OrgSlugauthenticatedPortalRouteRouteWithChildren
  '/org/$slug/settings': typeof OrgSlugauthenticatedSettingsRouteRouteWithChildren
  '/org/$slug/onboarding': typeof OrgSlugauthenticatedOnboardingRoute
  '/org/$slug/login': typeof OrgSlugunauthenticatedLoginRoute
  '/org/$slug/register': typeof OrgSlugunauthenticatedRegisterRoute
  '/org/$slug/': typeof OrgSlugauthenticatedIndexRoute
  '/org/$slug/admin/feed': typeof OrgSlugauthenticatedAdminFeedRoute
  '/org/$slug/portal/feed': typeof OrgSlugauthenticatedPortalFeedRoute
  '/org/$slug/admin/': typeof OrgSlugauthenticatedAdminIndexRoute
  '/org/$slug/portal/': typeof OrgSlugauthenticatedPortalIndexRoute
  '/org/$slug/settings/': typeof OrgSlugauthenticatedSettingsIndexRoute
  '/org/$slug/admin/boards/new': typeof OrgSlugauthenticatedAdminBoardsNewRoute
  '/org/$slug/admin/calendar/new': typeof OrgSlugauthenticatedAdminCalendarNewRoute
  '/org/$slug/admin/lessons/new': typeof OrgSlugauthenticatedAdminLessonsNewRoute
  '/org/$slug/admin/services/new': typeof OrgSlugauthenticatedAdminServicesNewRoute
  '/org/$slug/settings/account/availability': typeof OrgSlugauthenticatedSettingsAccountAvailabilityRoute
  '/org/$slug/settings/account/guardian': typeof OrgSlugauthenticatedSettingsAccountGuardianRoute
  '/org/$slug/settings/organization/business-hours': typeof OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute
  '/org/$slug/admin/boards/': typeof OrgSlugauthenticatedAdminBoardsIndexRoute
  '/org/$slug/admin/calendar/': typeof OrgSlugauthenticatedAdminCalendarIndexRoute
  '/org/$slug/admin/lessons/': typeof OrgSlugauthenticatedAdminLessonsIndexRoute
  '/org/$slug/admin/members/': typeof OrgSlugauthenticatedAdminMembersIndexRoute
  '/org/$slug/admin/services/': typeof OrgSlugauthenticatedAdminServicesIndexRoute
  '/org/$slug/portal/calendar/': typeof OrgSlugauthenticatedPortalCalendarIndexRoute
  '/org/$slug/admin/boards/$id/edit': typeof OrgSlugauthenticatedAdminBoardsIdEditRoute
  '/org/$slug/admin/members/riders/$riderId': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdRouteWithChildren
  '/org/$slug/admin/members/trainers/$trainerId': typeof OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute
  '/org/$slug/admin/services/$id/edit': typeof OrgSlugauthenticatedAdminServicesIdEditRoute
  '/org/$slug/settings/organization/questionnaires/new': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute
  '/org/$slug/admin/boards/$id/': typeof OrgSlugauthenticatedAdminBoardsIdIndexRoute
  '/org/$slug/admin/members/$id/': typeof OrgSlugauthenticatedAdminMembersIdIndexRoute
  '/org/$slug/admin/members/riders/': typeof OrgSlugauthenticatedAdminMembersRidersIndexRoute
  '/org/$slug/admin/members/trainers/': typeof OrgSlugauthenticatedAdminMembersTrainersIndexRoute
  '/org/$slug/admin/services/$id/': typeof OrgSlugauthenticatedAdminServicesIdIndexRoute
  '/org/$slug/settings/account/profile/': typeof OrgSlugauthenticatedSettingsAccountProfileIndexRoute
  '/org/$slug/settings/account/security/': typeof OrgSlugauthenticatedSettingsAccountSecurityIndexRoute
  '/org/$slug/settings/organization/general/': typeof OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute
  '/org/$slug/settings/organization/members/': typeof OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute
  '/org/$slug/settings/organization/questionnaires/': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute
  '/org/$slug/settings/organization/waivers/': typeof OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute
  '/org/$slug/admin/members/riders/$riderId/activity': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute
  '/org/$slug/settings/organization/questionnaires/$id/edit': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute
  '/org/$slug/admin/members/riders/$riderId/': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof authenticatedCreateOrganizationRoute
  '/join-organization': typeof authenticatedJoinOrganizationRoute
  '/login': typeof unauthenticatedLoginRoute
  '/register': typeof unauthenticatedRegisterRoute
  '/org/$slug': typeof OrgSlugauthenticatedIndexRoute
  '/org/$slug/onboarding': typeof OrgSlugauthenticatedOnboardingRoute
  '/org/$slug/login': typeof OrgSlugunauthenticatedLoginRoute
  '/org/$slug/register': typeof OrgSlugunauthenticatedRegisterRoute
  '/org/$slug/admin/feed': typeof OrgSlugauthenticatedAdminFeedRoute
  '/org/$slug/portal/feed': typeof OrgSlugauthenticatedPortalFeedRoute
  '/org/$slug/admin': typeof OrgSlugauthenticatedAdminIndexRoute
  '/org/$slug/portal': typeof OrgSlugauthenticatedPortalIndexRoute
  '/org/$slug/settings': typeof OrgSlugauthenticatedSettingsIndexRoute
  '/org/$slug/admin/boards/new': typeof OrgSlugauthenticatedAdminBoardsNewRoute
  '/org/$slug/admin/calendar/new': typeof OrgSlugauthenticatedAdminCalendarNewRoute
  '/org/$slug/admin/lessons/new': typeof OrgSlugauthenticatedAdminLessonsNewRoute
  '/org/$slug/admin/services/new': typeof OrgSlugauthenticatedAdminServicesNewRoute
  '/org/$slug/settings/account/availability': typeof OrgSlugauthenticatedSettingsAccountAvailabilityRoute
  '/org/$slug/settings/account/guardian': typeof OrgSlugauthenticatedSettingsAccountGuardianRoute
  '/org/$slug/settings/organization/business-hours': typeof OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute
  '/org/$slug/admin/boards': typeof OrgSlugauthenticatedAdminBoardsIndexRoute
  '/org/$slug/admin/calendar': typeof OrgSlugauthenticatedAdminCalendarIndexRoute
  '/org/$slug/admin/lessons': typeof OrgSlugauthenticatedAdminLessonsIndexRoute
  '/org/$slug/admin/members': typeof OrgSlugauthenticatedAdminMembersIndexRoute
  '/org/$slug/admin/services': typeof OrgSlugauthenticatedAdminServicesIndexRoute
  '/org/$slug/portal/calendar': typeof OrgSlugauthenticatedPortalCalendarIndexRoute
  '/org/$slug/admin/boards/$id/edit': typeof OrgSlugauthenticatedAdminBoardsIdEditRoute
  '/org/$slug/admin/members/trainers/$trainerId': typeof OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute
  '/org/$slug/admin/services/$id/edit': typeof OrgSlugauthenticatedAdminServicesIdEditRoute
  '/org/$slug/settings/organization/questionnaires/new': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute
  '/org/$slug/admin/boards/$id': typeof OrgSlugauthenticatedAdminBoardsIdIndexRoute
  '/org/$slug/admin/members/$id': typeof OrgSlugauthenticatedAdminMembersIdIndexRoute
  '/org/$slug/admin/members/riders': typeof OrgSlugauthenticatedAdminMembersRidersIndexRoute
  '/org/$slug/admin/members/trainers': typeof OrgSlugauthenticatedAdminMembersTrainersIndexRoute
  '/org/$slug/admin/services/$id': typeof OrgSlugauthenticatedAdminServicesIdIndexRoute
  '/org/$slug/settings/account/profile': typeof OrgSlugauthenticatedSettingsAccountProfileIndexRoute
  '/org/$slug/settings/account/security': typeof OrgSlugauthenticatedSettingsAccountSecurityIndexRoute
  '/org/$slug/settings/organization/general': typeof OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute
  '/org/$slug/settings/organization/members': typeof OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute
  '/org/$slug/settings/organization/questionnaires': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute
  '/org/$slug/settings/organization/waivers': typeof OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute
  '/org/$slug/admin/members/riders/$riderId/activity': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute
  '/org/$slug/settings/organization/questionnaires/$id/edit': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute
  '/org/$slug/admin/members/riders/$riderId': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/(authenticated)/create-organization': typeof authenticatedCreateOrganizationRoute
  '/(authenticated)/join-organization': typeof authenticatedJoinOrganizationRoute
  '/(unauthenticated)/login': typeof unauthenticatedLoginRoute
  '/(unauthenticated)/register': typeof unauthenticatedRegisterRoute
  '/org/$slug': typeof OrgSlugRouteWithChildren
  '/org/$slug/(authenticated)': typeof OrgSlugauthenticatedRouteRouteWithChildren
  '/org/$slug/(unauthenticated)': typeof OrgSlugunauthenticatedRouteRouteWithChildren
  '/org/$slug/(authenticated)/admin': typeof OrgSlugauthenticatedAdminRouteRouteWithChildren
  '/org/$slug/(authenticated)/portal': typeof OrgSlugauthenticatedPortalRouteRouteWithChildren
  '/org/$slug/(authenticated)/settings': typeof OrgSlugauthenticatedSettingsRouteRouteWithChildren
  '/org/$slug/(authenticated)/onboarding': typeof OrgSlugauthenticatedOnboardingRoute
  '/org/$slug/(unauthenticated)/login': typeof OrgSlugunauthenticatedLoginRoute
  '/org/$slug/(unauthenticated)/register': typeof OrgSlugunauthenticatedRegisterRoute
  '/org/$slug/(authenticated)/': typeof OrgSlugauthenticatedIndexRoute
  '/org/$slug/(authenticated)/admin/feed': typeof OrgSlugauthenticatedAdminFeedRoute
  '/org/$slug/(authenticated)/portal/feed': typeof OrgSlugauthenticatedPortalFeedRoute
  '/org/$slug/(authenticated)/admin/': typeof OrgSlugauthenticatedAdminIndexRoute
  '/org/$slug/(authenticated)/portal/': typeof OrgSlugauthenticatedPortalIndexRoute
  '/org/$slug/(authenticated)/settings/': typeof OrgSlugauthenticatedSettingsIndexRoute
  '/org/$slug/(authenticated)/admin/boards/new': typeof OrgSlugauthenticatedAdminBoardsNewRoute
  '/org/$slug/(authenticated)/admin/calendar/new': typeof OrgSlugauthenticatedAdminCalendarNewRoute
  '/org/$slug/(authenticated)/admin/lessons/new': typeof OrgSlugauthenticatedAdminLessonsNewRoute
  '/org/$slug/(authenticated)/admin/services/new': typeof OrgSlugauthenticatedAdminServicesNewRoute
  '/org/$slug/(authenticated)/settings/account/availability': typeof OrgSlugauthenticatedSettingsAccountAvailabilityRoute
  '/org/$slug/(authenticated)/settings/account/guardian': typeof OrgSlugauthenticatedSettingsAccountGuardianRoute
  '/org/$slug/(authenticated)/settings/organization/business-hours': typeof OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute
  '/org/$slug/(authenticated)/admin/boards/': typeof OrgSlugauthenticatedAdminBoardsIndexRoute
  '/org/$slug/(authenticated)/admin/calendar/': typeof OrgSlugauthenticatedAdminCalendarIndexRoute
  '/org/$slug/(authenticated)/admin/lessons/': typeof OrgSlugauthenticatedAdminLessonsIndexRoute
  '/org/$slug/(authenticated)/admin/members/': typeof OrgSlugauthenticatedAdminMembersIndexRoute
  '/org/$slug/(authenticated)/admin/services/': typeof OrgSlugauthenticatedAdminServicesIndexRoute
  '/org/$slug/(authenticated)/portal/calendar/': typeof OrgSlugauthenticatedPortalCalendarIndexRoute
  '/org/$slug/(authenticated)/admin/boards/$id/edit': typeof OrgSlugauthenticatedAdminBoardsIdEditRoute
  '/org/$slug/(authenticated)/admin/members/riders/$riderId': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdRouteWithChildren
  '/org/$slug/(authenticated)/admin/members/trainers/$trainerId': typeof OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute
  '/org/$slug/(authenticated)/admin/services/$id/edit': typeof OrgSlugauthenticatedAdminServicesIdEditRoute
  '/org/$slug/(authenticated)/settings/organization/questionnaires/new': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute
  '/org/$slug/(authenticated)/admin/boards/$id/': typeof OrgSlugauthenticatedAdminBoardsIdIndexRoute
  '/org/$slug/(authenticated)/admin/members/$id/': typeof OrgSlugauthenticatedAdminMembersIdIndexRoute
  '/org/$slug/(authenticated)/admin/members/riders/': typeof OrgSlugauthenticatedAdminMembersRidersIndexRoute
  '/org/$slug/(authenticated)/admin/members/trainers/': typeof OrgSlugauthenticatedAdminMembersTrainersIndexRoute
  '/org/$slug/(authenticated)/admin/services/$id/': typeof OrgSlugauthenticatedAdminServicesIdIndexRoute
  '/org/$slug/(authenticated)/settings/account/profile/': typeof OrgSlugauthenticatedSettingsAccountProfileIndexRoute
  '/org/$slug/(authenticated)/settings/account/security/': typeof OrgSlugauthenticatedSettingsAccountSecurityIndexRoute
  '/org/$slug/(authenticated)/settings/organization/general/': typeof OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute
  '/org/$slug/(authenticated)/settings/organization/members/': typeof OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute
  '/org/$slug/(authenticated)/settings/organization/questionnaires/': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute
  '/org/$slug/(authenticated)/settings/organization/waivers/': typeof OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute
  '/org/$slug/(authenticated)/admin/members/riders/$riderId/activity': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute
  '/org/$slug/(authenticated)/settings/organization/questionnaires/$id/edit': typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute
  '/org/$slug/(authenticated)/admin/members/riders/$riderId/': typeof OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/join-organization'
    | '/login'
    | '/register'
    | '/org/$slug'
    | '/org/$slug/admin'
    | '/org/$slug/portal'
    | '/org/$slug/settings'
    | '/org/$slug/onboarding'
    | '/org/$slug/login'
    | '/org/$slug/register'
    | '/org/$slug/'
    | '/org/$slug/admin/feed'
    | '/org/$slug/portal/feed'
    | '/org/$slug/admin/'
    | '/org/$slug/portal/'
    | '/org/$slug/settings/'
    | '/org/$slug/admin/boards/new'
    | '/org/$slug/admin/calendar/new'
    | '/org/$slug/admin/lessons/new'
    | '/org/$slug/admin/services/new'
    | '/org/$slug/settings/account/availability'
    | '/org/$slug/settings/account/guardian'
    | '/org/$slug/settings/organization/business-hours'
    | '/org/$slug/admin/boards/'
    | '/org/$slug/admin/calendar/'
    | '/org/$slug/admin/lessons/'
    | '/org/$slug/admin/members/'
    | '/org/$slug/admin/services/'
    | '/org/$slug/portal/calendar/'
    | '/org/$slug/admin/boards/$id/edit'
    | '/org/$slug/admin/members/riders/$riderId'
    | '/org/$slug/admin/members/trainers/$trainerId'
    | '/org/$slug/admin/services/$id/edit'
    | '/org/$slug/settings/organization/questionnaires/new'
    | '/org/$slug/admin/boards/$id/'
    | '/org/$slug/admin/members/$id/'
    | '/org/$slug/admin/members/riders/'
    | '/org/$slug/admin/members/trainers/'
    | '/org/$slug/admin/services/$id/'
    | '/org/$slug/settings/account/profile/'
    | '/org/$slug/settings/account/security/'
    | '/org/$slug/settings/organization/general/'
    | '/org/$slug/settings/organization/members/'
    | '/org/$slug/settings/organization/questionnaires/'
    | '/org/$slug/settings/organization/waivers/'
    | '/org/$slug/admin/members/riders/$riderId/activity'
    | '/org/$slug/settings/organization/questionnaires/$id/edit'
    | '/org/$slug/admin/members/riders/$riderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/join-organization'
    | '/login'
    | '/register'
    | '/org/$slug'
    | '/org/$slug/onboarding'
    | '/org/$slug/login'
    | '/org/$slug/register'
    | '/org/$slug/admin/feed'
    | '/org/$slug/portal/feed'
    | '/org/$slug/admin'
    | '/org/$slug/portal'
    | '/org/$slug/settings'
    | '/org/$slug/admin/boards/new'
    | '/org/$slug/admin/calendar/new'
    | '/org/$slug/admin/lessons/new'
    | '/org/$slug/admin/services/new'
    | '/org/$slug/settings/account/availability'
    | '/org/$slug/settings/account/guardian'
    | '/org/$slug/settings/organization/business-hours'
    | '/org/$slug/admin/boards'
    | '/org/$slug/admin/calendar'
    | '/org/$slug/admin/lessons'
    | '/org/$slug/admin/members'
    | '/org/$slug/admin/services'
    | '/org/$slug/portal/calendar'
    | '/org/$slug/admin/boards/$id/edit'
    | '/org/$slug/admin/members/trainers/$trainerId'
    | '/org/$slug/admin/services/$id/edit'
    | '/org/$slug/settings/organization/questionnaires/new'
    | '/org/$slug/admin/boards/$id'
    | '/org/$slug/admin/members/$id'
    | '/org/$slug/admin/members/riders'
    | '/org/$slug/admin/members/trainers'
    | '/org/$slug/admin/services/$id'
    | '/org/$slug/settings/account/profile'
    | '/org/$slug/settings/account/security'
    | '/org/$slug/settings/organization/general'
    | '/org/$slug/settings/organization/members'
    | '/org/$slug/settings/organization/questionnaires'
    | '/org/$slug/settings/organization/waivers'
    | '/org/$slug/admin/members/riders/$riderId/activity'
    | '/org/$slug/settings/organization/questionnaires/$id/edit'
    | '/org/$slug/admin/members/riders/$riderId'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(unauthenticated)'
    | '/(authenticated)/create-organization'
    | '/(authenticated)/join-organization'
    | '/(unauthenticated)/login'
    | '/(unauthenticated)/register'
    | '/org/$slug'
    | '/org/$slug/(authenticated)'
    | '/org/$slug/(unauthenticated)'
    | '/org/$slug/(authenticated)/admin'
    | '/org/$slug/(authenticated)/portal'
    | '/org/$slug/(authenticated)/settings'
    | '/org/$slug/(authenticated)/onboarding'
    | '/org/$slug/(unauthenticated)/login'
    | '/org/$slug/(unauthenticated)/register'
    | '/org/$slug/(authenticated)/'
    | '/org/$slug/(authenticated)/admin/feed'
    | '/org/$slug/(authenticated)/portal/feed'
    | '/org/$slug/(authenticated)/admin/'
    | '/org/$slug/(authenticated)/portal/'
    | '/org/$slug/(authenticated)/settings/'
    | '/org/$slug/(authenticated)/admin/boards/new'
    | '/org/$slug/(authenticated)/admin/calendar/new'
    | '/org/$slug/(authenticated)/admin/lessons/new'
    | '/org/$slug/(authenticated)/admin/services/new'
    | '/org/$slug/(authenticated)/settings/account/availability'
    | '/org/$slug/(authenticated)/settings/account/guardian'
    | '/org/$slug/(authenticated)/settings/organization/business-hours'
    | '/org/$slug/(authenticated)/admin/boards/'
    | '/org/$slug/(authenticated)/admin/calendar/'
    | '/org/$slug/(authenticated)/admin/lessons/'
    | '/org/$slug/(authenticated)/admin/members/'
    | '/org/$slug/(authenticated)/admin/services/'
    | '/org/$slug/(authenticated)/portal/calendar/'
    | '/org/$slug/(authenticated)/admin/boards/$id/edit'
    | '/org/$slug/(authenticated)/admin/members/riders/$riderId'
    | '/org/$slug/(authenticated)/admin/members/trainers/$trainerId'
    | '/org/$slug/(authenticated)/admin/services/$id/edit'
    | '/org/$slug/(authenticated)/settings/organization/questionnaires/new'
    | '/org/$slug/(authenticated)/admin/boards/$id/'
    | '/org/$slug/(authenticated)/admin/members/$id/'
    | '/org/$slug/(authenticated)/admin/members/riders/'
    | '/org/$slug/(authenticated)/admin/members/trainers/'
    | '/org/$slug/(authenticated)/admin/services/$id/'
    | '/org/$slug/(authenticated)/settings/account/profile/'
    | '/org/$slug/(authenticated)/settings/account/security/'
    | '/org/$slug/(authenticated)/settings/organization/general/'
    | '/org/$slug/(authenticated)/settings/organization/members/'
    | '/org/$slug/(authenticated)/settings/organization/questionnaires/'
    | '/org/$slug/(authenticated)/settings/organization/waivers/'
    | '/org/$slug/(authenticated)/admin/members/riders/$riderId/activity'
    | '/org/$slug/(authenticated)/settings/organization/questionnaires/$id/edit'
    | '/org/$slug/(authenticated)/admin/members/riders/$riderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthenticated)/register': {
      id: '/(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof unauthenticatedRegisterRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/login': {
      id: '/(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(authenticated)/join-organization': {
      id: '/(authenticated)/join-organization'
      path: '/join-organization'
      fullPath: '/join-organization'
      preLoaderRoute: typeof authenticatedJoinOrganizationRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/create-organization': {
      id: '/(authenticated)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof authenticatedCreateOrganizationRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/org/$slug/(unauthenticated)': {
      id: '/org/$slug/(unauthenticated)'
      path: ''
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugunauthenticatedRouteRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/(authenticated)': {
      id: '/org/$slug/(authenticated)'
      path: ''
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugauthenticatedRouteRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/org/$slug/(authenticated)/': {
      id: '/org/$slug/(authenticated)/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugauthenticatedIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedRouteRoute
    }
    '/org/$slug/(unauthenticated)/register': {
      id: '/org/$slug/(unauthenticated)/register'
      path: '/register'
      fullPath: '/org/$slug/register'
      preLoaderRoute: typeof OrgSlugunauthenticatedRegisterRouteImport
      parentRoute: typeof OrgSlugunauthenticatedRouteRoute
    }
    '/org/$slug/(unauthenticated)/login': {
      id: '/org/$slug/(unauthenticated)/login'
      path: '/login'
      fullPath: '/org/$slug/login'
      preLoaderRoute: typeof OrgSlugunauthenticatedLoginRouteImport
      parentRoute: typeof OrgSlugunauthenticatedRouteRoute
    }
    '/org/$slug/(authenticated)/onboarding': {
      id: '/org/$slug/(authenticated)/onboarding'
      path: '/onboarding'
      fullPath: '/org/$slug/onboarding'
      preLoaderRoute: typeof OrgSlugauthenticatedOnboardingRouteImport
      parentRoute: typeof OrgSlugauthenticatedRouteRoute
    }
    '/org/$slug/(authenticated)/settings': {
      id: '/org/$slug/(authenticated)/settings'
      path: '/settings'
      fullPath: '/org/$slug/settings'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsRouteRouteImport
      parentRoute: typeof OrgSlugauthenticatedRouteRoute
    }
    '/org/$slug/(authenticated)/portal': {
      id: '/org/$slug/(authenticated)/portal'
      path: '/portal'
      fullPath: '/org/$slug/portal'
      preLoaderRoute: typeof OrgSlugauthenticatedPortalRouteRouteImport
      parentRoute: typeof OrgSlugauthenticatedRouteRoute
    }
    '/org/$slug/(authenticated)/admin': {
      id: '/org/$slug/(authenticated)/admin'
      path: '/admin'
      fullPath: '/org/$slug/admin'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminRouteRouteImport
      parentRoute: typeof OrgSlugauthenticatedRouteRoute
    }
    '/org/$slug/(authenticated)/settings/': {
      id: '/org/$slug/(authenticated)/settings/'
      path: '/'
      fullPath: '/org/$slug/settings/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/portal/': {
      id: '/org/$slug/(authenticated)/portal/'
      path: '/'
      fullPath: '/org/$slug/portal/'
      preLoaderRoute: typeof OrgSlugauthenticatedPortalIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedPortalRouteRoute
    }
    '/org/$slug/(authenticated)/admin/': {
      id: '/org/$slug/(authenticated)/admin/'
      path: '/'
      fullPath: '/org/$slug/admin/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/portal/feed': {
      id: '/org/$slug/(authenticated)/portal/feed'
      path: '/feed'
      fullPath: '/org/$slug/portal/feed'
      preLoaderRoute: typeof OrgSlugauthenticatedPortalFeedRouteImport
      parentRoute: typeof OrgSlugauthenticatedPortalRouteRoute
    }
    '/org/$slug/(authenticated)/admin/feed': {
      id: '/org/$slug/(authenticated)/admin/feed'
      path: '/feed'
      fullPath: '/org/$slug/admin/feed'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminFeedRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/portal/calendar/': {
      id: '/org/$slug/(authenticated)/portal/calendar/'
      path: '/calendar'
      fullPath: '/org/$slug/portal/calendar/'
      preLoaderRoute: typeof OrgSlugauthenticatedPortalCalendarIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedPortalRouteRoute
    }
    '/org/$slug/(authenticated)/admin/services/': {
      id: '/org/$slug/(authenticated)/admin/services/'
      path: '/services'
      fullPath: '/org/$slug/admin/services/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminServicesIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/': {
      id: '/org/$slug/(authenticated)/admin/members/'
      path: '/members'
      fullPath: '/org/$slug/admin/members/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/lessons/': {
      id: '/org/$slug/(authenticated)/admin/lessons/'
      path: '/lessons'
      fullPath: '/org/$slug/admin/lessons/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminLessonsIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/calendar/': {
      id: '/org/$slug/(authenticated)/admin/calendar/'
      path: '/calendar'
      fullPath: '/org/$slug/admin/calendar/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminCalendarIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/boards/': {
      id: '/org/$slug/(authenticated)/admin/boards/'
      path: '/boards'
      fullPath: '/org/$slug/admin/boards/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminBoardsIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/settings/organization/business-hours': {
      id: '/org/$slug/(authenticated)/settings/organization/business-hours'
      path: '/organization/business-hours'
      fullPath: '/org/$slug/settings/organization/business-hours'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationBusinessHoursRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/account/guardian': {
      id: '/org/$slug/(authenticated)/settings/account/guardian'
      path: '/account/guardian'
      fullPath: '/org/$slug/settings/account/guardian'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsAccountGuardianRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/account/availability': {
      id: '/org/$slug/(authenticated)/settings/account/availability'
      path: '/account/availability'
      fullPath: '/org/$slug/settings/account/availability'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsAccountAvailabilityRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/admin/services/new': {
      id: '/org/$slug/(authenticated)/admin/services/new'
      path: '/services/new'
      fullPath: '/org/$slug/admin/services/new'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminServicesNewRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/lessons/new': {
      id: '/org/$slug/(authenticated)/admin/lessons/new'
      path: '/lessons/new'
      fullPath: '/org/$slug/admin/lessons/new'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminLessonsNewRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/calendar/new': {
      id: '/org/$slug/(authenticated)/admin/calendar/new'
      path: '/calendar/new'
      fullPath: '/org/$slug/admin/calendar/new'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminCalendarNewRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/boards/new': {
      id: '/org/$slug/(authenticated)/admin/boards/new'
      path: '/boards/new'
      fullPath: '/org/$slug/admin/boards/new'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminBoardsNewRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/settings/organization/waivers/': {
      id: '/org/$slug/(authenticated)/settings/organization/waivers/'
      path: '/organization/waivers'
      fullPath: '/org/$slug/settings/organization/waivers/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationWaiversIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/organization/questionnaires/': {
      id: '/org/$slug/(authenticated)/settings/organization/questionnaires/'
      path: '/organization/questionnaires'
      fullPath: '/org/$slug/settings/organization/questionnaires/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/organization/members/': {
      id: '/org/$slug/(authenticated)/settings/organization/members/'
      path: '/organization/members'
      fullPath: '/org/$slug/settings/organization/members/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationMembersIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/organization/general/': {
      id: '/org/$slug/(authenticated)/settings/organization/general/'
      path: '/organization/general'
      fullPath: '/org/$slug/settings/organization/general/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationGeneralIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/account/security/': {
      id: '/org/$slug/(authenticated)/settings/account/security/'
      path: '/account/security'
      fullPath: '/org/$slug/settings/account/security/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsAccountSecurityIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/settings/account/profile/': {
      id: '/org/$slug/(authenticated)/settings/account/profile/'
      path: '/account/profile'
      fullPath: '/org/$slug/settings/account/profile/'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsAccountProfileIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/admin/services/$id/': {
      id: '/org/$slug/(authenticated)/admin/services/$id/'
      path: '/services/$id'
      fullPath: '/org/$slug/admin/services/$id/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminServicesIdIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/trainers/': {
      id: '/org/$slug/(authenticated)/admin/members/trainers/'
      path: '/members/trainers'
      fullPath: '/org/$slug/admin/members/trainers/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersTrainersIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/riders/': {
      id: '/org/$slug/(authenticated)/admin/members/riders/'
      path: '/members/riders'
      fullPath: '/org/$slug/admin/members/riders/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersRidersIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/$id/': {
      id: '/org/$slug/(authenticated)/admin/members/$id/'
      path: '/members/$id'
      fullPath: '/org/$slug/admin/members/$id/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersIdIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/boards/$id/': {
      id: '/org/$slug/(authenticated)/admin/boards/$id/'
      path: '/boards/$id'
      fullPath: '/org/$slug/admin/boards/$id/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminBoardsIdIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/settings/organization/questionnaires/new': {
      id: '/org/$slug/(authenticated)/settings/organization/questionnaires/new'
      path: '/organization/questionnaires/new'
      fullPath: '/org/$slug/settings/organization/questionnaires/new'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/admin/services/$id/edit': {
      id: '/org/$slug/(authenticated)/admin/services/$id/edit'
      path: '/services/$id/edit'
      fullPath: '/org/$slug/admin/services/$id/edit'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminServicesIdEditRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/trainers/$trainerId': {
      id: '/org/$slug/(authenticated)/admin/members/trainers/$trainerId'
      path: '/members/trainers/$trainerId'
      fullPath: '/org/$slug/admin/members/trainers/$trainerId'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersTrainersTrainerIdRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/riders/$riderId': {
      id: '/org/$slug/(authenticated)/admin/members/riders/$riderId'
      path: '/members/riders/$riderId'
      fullPath: '/org/$slug/admin/members/riders/$riderId'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/boards/$id/edit': {
      id: '/org/$slug/(authenticated)/admin/boards/$id/edit'
      path: '/boards/$id/edit'
      fullPath: '/org/$slug/admin/boards/$id/edit'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminBoardsIdEditRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/riders/$riderId/': {
      id: '/org/$slug/(authenticated)/admin/members/riders/$riderId/'
      path: '/'
      fullPath: '/org/$slug/admin/members/riders/$riderId/'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdRoute
    }
    '/org/$slug/(authenticated)/settings/organization/questionnaires/$id/edit': {
      id: '/org/$slug/(authenticated)/settings/organization/questionnaires/$id/edit'
      path: '/organization/questionnaires/$id/edit'
      fullPath: '/org/$slug/settings/organization/questionnaires/$id/edit'
      preLoaderRoute: typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRouteImport
      parentRoute: typeof OrgSlugauthenticatedSettingsRouteRoute
    }
    '/org/$slug/(authenticated)/admin/members/riders/$riderId/activity': {
      id: '/org/$slug/(authenticated)/admin/members/riders/$riderId/activity'
      path: '/activity'
      fullPath: '/org/$slug/admin/members/riders/$riderId/activity'
      preLoaderRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRouteImport
      parentRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedCreateOrganizationRoute: typeof authenticatedCreateOrganizationRoute
  authenticatedJoinOrganizationRoute: typeof authenticatedJoinOrganizationRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedCreateOrganizationRoute: authenticatedCreateOrganizationRoute,
  authenticatedJoinOrganizationRoute: authenticatedJoinOrganizationRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
  unauthenticatedRegisterRoute: typeof unauthenticatedRegisterRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
  unauthenticatedRegisterRoute: unauthenticatedRegisterRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

interface OrgSlugauthenticatedAdminMembersRidersRiderIdRouteChildren {
  OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute
  OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute
}

const OrgSlugauthenticatedAdminMembersRidersRiderIdRouteChildren: OrgSlugauthenticatedAdminMembersRidersRiderIdRouteChildren =
  {
    OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute:
      OrgSlugauthenticatedAdminMembersRidersRiderIdActivityRoute,
    OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute:
      OrgSlugauthenticatedAdminMembersRidersRiderIdIndexRoute,
  }

const OrgSlugauthenticatedAdminMembersRidersRiderIdRouteWithChildren =
  OrgSlugauthenticatedAdminMembersRidersRiderIdRoute._addFileChildren(
    OrgSlugauthenticatedAdminMembersRidersRiderIdRouteChildren,
  )

interface OrgSlugauthenticatedAdminRouteRouteChildren {
  OrgSlugauthenticatedAdminFeedRoute: typeof OrgSlugauthenticatedAdminFeedRoute
  OrgSlugauthenticatedAdminIndexRoute: typeof OrgSlugauthenticatedAdminIndexRoute
  OrgSlugauthenticatedAdminBoardsNewRoute: typeof OrgSlugauthenticatedAdminBoardsNewRoute
  OrgSlugauthenticatedAdminCalendarNewRoute: typeof OrgSlugauthenticatedAdminCalendarNewRoute
  OrgSlugauthenticatedAdminLessonsNewRoute: typeof OrgSlugauthenticatedAdminLessonsNewRoute
  OrgSlugauthenticatedAdminServicesNewRoute: typeof OrgSlugauthenticatedAdminServicesNewRoute
  OrgSlugauthenticatedAdminBoardsIndexRoute: typeof OrgSlugauthenticatedAdminBoardsIndexRoute
  OrgSlugauthenticatedAdminCalendarIndexRoute: typeof OrgSlugauthenticatedAdminCalendarIndexRoute
  OrgSlugauthenticatedAdminLessonsIndexRoute: typeof OrgSlugauthenticatedAdminLessonsIndexRoute
  OrgSlugauthenticatedAdminMembersIndexRoute: typeof OrgSlugauthenticatedAdminMembersIndexRoute
  OrgSlugauthenticatedAdminServicesIndexRoute: typeof OrgSlugauthenticatedAdminServicesIndexRoute
  OrgSlugauthenticatedAdminBoardsIdEditRoute: typeof OrgSlugauthenticatedAdminBoardsIdEditRoute
  OrgSlugauthenticatedAdminMembersRidersRiderIdRoute: typeof OrgSlugauthenticatedAdminMembersRidersRiderIdRouteWithChildren
  OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute: typeof OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute
  OrgSlugauthenticatedAdminServicesIdEditRoute: typeof OrgSlugauthenticatedAdminServicesIdEditRoute
  OrgSlugauthenticatedAdminBoardsIdIndexRoute: typeof OrgSlugauthenticatedAdminBoardsIdIndexRoute
  OrgSlugauthenticatedAdminMembersIdIndexRoute: typeof OrgSlugauthenticatedAdminMembersIdIndexRoute
  OrgSlugauthenticatedAdminMembersRidersIndexRoute: typeof OrgSlugauthenticatedAdminMembersRidersIndexRoute
  OrgSlugauthenticatedAdminMembersTrainersIndexRoute: typeof OrgSlugauthenticatedAdminMembersTrainersIndexRoute
  OrgSlugauthenticatedAdminServicesIdIndexRoute: typeof OrgSlugauthenticatedAdminServicesIdIndexRoute
}

const OrgSlugauthenticatedAdminRouteRouteChildren: OrgSlugauthenticatedAdminRouteRouteChildren =
  {
    OrgSlugauthenticatedAdminFeedRoute: OrgSlugauthenticatedAdminFeedRoute,
    OrgSlugauthenticatedAdminIndexRoute: OrgSlugauthenticatedAdminIndexRoute,
    OrgSlugauthenticatedAdminBoardsNewRoute:
      OrgSlugauthenticatedAdminBoardsNewRoute,
    OrgSlugauthenticatedAdminCalendarNewRoute:
      OrgSlugauthenticatedAdminCalendarNewRoute,
    OrgSlugauthenticatedAdminLessonsNewRoute:
      OrgSlugauthenticatedAdminLessonsNewRoute,
    OrgSlugauthenticatedAdminServicesNewRoute:
      OrgSlugauthenticatedAdminServicesNewRoute,
    OrgSlugauthenticatedAdminBoardsIndexRoute:
      OrgSlugauthenticatedAdminBoardsIndexRoute,
    OrgSlugauthenticatedAdminCalendarIndexRoute:
      OrgSlugauthenticatedAdminCalendarIndexRoute,
    OrgSlugauthenticatedAdminLessonsIndexRoute:
      OrgSlugauthenticatedAdminLessonsIndexRoute,
    OrgSlugauthenticatedAdminMembersIndexRoute:
      OrgSlugauthenticatedAdminMembersIndexRoute,
    OrgSlugauthenticatedAdminServicesIndexRoute:
      OrgSlugauthenticatedAdminServicesIndexRoute,
    OrgSlugauthenticatedAdminBoardsIdEditRoute:
      OrgSlugauthenticatedAdminBoardsIdEditRoute,
    OrgSlugauthenticatedAdminMembersRidersRiderIdRoute:
      OrgSlugauthenticatedAdminMembersRidersRiderIdRouteWithChildren,
    OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute:
      OrgSlugauthenticatedAdminMembersTrainersTrainerIdRoute,
    OrgSlugauthenticatedAdminServicesIdEditRoute:
      OrgSlugauthenticatedAdminServicesIdEditRoute,
    OrgSlugauthenticatedAdminBoardsIdIndexRoute:
      OrgSlugauthenticatedAdminBoardsIdIndexRoute,
    OrgSlugauthenticatedAdminMembersIdIndexRoute:
      OrgSlugauthenticatedAdminMembersIdIndexRoute,
    OrgSlugauthenticatedAdminMembersRidersIndexRoute:
      OrgSlugauthenticatedAdminMembersRidersIndexRoute,
    OrgSlugauthenticatedAdminMembersTrainersIndexRoute:
      OrgSlugauthenticatedAdminMembersTrainersIndexRoute,
    OrgSlugauthenticatedAdminServicesIdIndexRoute:
      OrgSlugauthenticatedAdminServicesIdIndexRoute,
  }

const OrgSlugauthenticatedAdminRouteRouteWithChildren =
  OrgSlugauthenticatedAdminRouteRoute._addFileChildren(
    OrgSlugauthenticatedAdminRouteRouteChildren,
  )

interface OrgSlugauthenticatedPortalRouteRouteChildren {
  OrgSlugauthenticatedPortalFeedRoute: typeof OrgSlugauthenticatedPortalFeedRoute
  OrgSlugauthenticatedPortalIndexRoute: typeof OrgSlugauthenticatedPortalIndexRoute
  OrgSlugauthenticatedPortalCalendarIndexRoute: typeof OrgSlugauthenticatedPortalCalendarIndexRoute
}

const OrgSlugauthenticatedPortalRouteRouteChildren: OrgSlugauthenticatedPortalRouteRouteChildren =
  {
    OrgSlugauthenticatedPortalFeedRoute: OrgSlugauthenticatedPortalFeedRoute,
    OrgSlugauthenticatedPortalIndexRoute: OrgSlugauthenticatedPortalIndexRoute,
    OrgSlugauthenticatedPortalCalendarIndexRoute:
      OrgSlugauthenticatedPortalCalendarIndexRoute,
  }

const OrgSlugauthenticatedPortalRouteRouteWithChildren =
  OrgSlugauthenticatedPortalRouteRoute._addFileChildren(
    OrgSlugauthenticatedPortalRouteRouteChildren,
  )

interface OrgSlugauthenticatedSettingsRouteRouteChildren {
  OrgSlugauthenticatedSettingsIndexRoute: typeof OrgSlugauthenticatedSettingsIndexRoute
  OrgSlugauthenticatedSettingsAccountAvailabilityRoute: typeof OrgSlugauthenticatedSettingsAccountAvailabilityRoute
  OrgSlugauthenticatedSettingsAccountGuardianRoute: typeof OrgSlugauthenticatedSettingsAccountGuardianRoute
  OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute: typeof OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute
  OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute: typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute
  OrgSlugauthenticatedSettingsAccountProfileIndexRoute: typeof OrgSlugauthenticatedSettingsAccountProfileIndexRoute
  OrgSlugauthenticatedSettingsAccountSecurityIndexRoute: typeof OrgSlugauthenticatedSettingsAccountSecurityIndexRoute
  OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute: typeof OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute
  OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute: typeof OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute
  OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute: typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute
  OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute: typeof OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute
  OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute: typeof OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute
}

const OrgSlugauthenticatedSettingsRouteRouteChildren: OrgSlugauthenticatedSettingsRouteRouteChildren =
  {
    OrgSlugauthenticatedSettingsIndexRoute:
      OrgSlugauthenticatedSettingsIndexRoute,
    OrgSlugauthenticatedSettingsAccountAvailabilityRoute:
      OrgSlugauthenticatedSettingsAccountAvailabilityRoute,
    OrgSlugauthenticatedSettingsAccountGuardianRoute:
      OrgSlugauthenticatedSettingsAccountGuardianRoute,
    OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute:
      OrgSlugauthenticatedSettingsOrganizationBusinessHoursRoute,
    OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute:
      OrgSlugauthenticatedSettingsOrganizationQuestionnairesNewRoute,
    OrgSlugauthenticatedSettingsAccountProfileIndexRoute:
      OrgSlugauthenticatedSettingsAccountProfileIndexRoute,
    OrgSlugauthenticatedSettingsAccountSecurityIndexRoute:
      OrgSlugauthenticatedSettingsAccountSecurityIndexRoute,
    OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute:
      OrgSlugauthenticatedSettingsOrganizationGeneralIndexRoute,
    OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute:
      OrgSlugauthenticatedSettingsOrganizationMembersIndexRoute,
    OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute:
      OrgSlugauthenticatedSettingsOrganizationQuestionnairesIndexRoute,
    OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute:
      OrgSlugauthenticatedSettingsOrganizationWaiversIndexRoute,
    OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute:
      OrgSlugauthenticatedSettingsOrganizationQuestionnairesIdEditRoute,
  }

const OrgSlugauthenticatedSettingsRouteRouteWithChildren =
  OrgSlugauthenticatedSettingsRouteRoute._addFileChildren(
    OrgSlugauthenticatedSettingsRouteRouteChildren,
  )

interface OrgSlugauthenticatedRouteRouteChildren {
  OrgSlugauthenticatedAdminRouteRoute: typeof OrgSlugauthenticatedAdminRouteRouteWithChildren
  OrgSlugauthenticatedPortalRouteRoute: typeof OrgSlugauthenticatedPortalRouteRouteWithChildren
  OrgSlugauthenticatedSettingsRouteRoute: typeof OrgSlugauthenticatedSettingsRouteRouteWithChildren
  OrgSlugauthenticatedOnboardingRoute: typeof OrgSlugauthenticatedOnboardingRoute
  OrgSlugauthenticatedIndexRoute: typeof OrgSlugauthenticatedIndexRoute
}

const OrgSlugauthenticatedRouteRouteChildren: OrgSlugauthenticatedRouteRouteChildren =
  {
    OrgSlugauthenticatedAdminRouteRoute:
      OrgSlugauthenticatedAdminRouteRouteWithChildren,
    OrgSlugauthenticatedPortalRouteRoute:
      OrgSlugauthenticatedPortalRouteRouteWithChildren,
    OrgSlugauthenticatedSettingsRouteRoute:
      OrgSlugauthenticatedSettingsRouteRouteWithChildren,
    OrgSlugauthenticatedOnboardingRoute: OrgSlugauthenticatedOnboardingRoute,
    OrgSlugauthenticatedIndexRoute: OrgSlugauthenticatedIndexRoute,
  }

const OrgSlugauthenticatedRouteRouteWithChildren =
  OrgSlugauthenticatedRouteRoute._addFileChildren(
    OrgSlugauthenticatedRouteRouteChildren,
  )

interface OrgSlugunauthenticatedRouteRouteChildren {
  OrgSlugunauthenticatedLoginRoute: typeof OrgSlugunauthenticatedLoginRoute
  OrgSlugunauthenticatedRegisterRoute: typeof OrgSlugunauthenticatedRegisterRoute
}

const OrgSlugunauthenticatedRouteRouteChildren: OrgSlugunauthenticatedRouteRouteChildren =
  {
    OrgSlugunauthenticatedLoginRoute: OrgSlugunauthenticatedLoginRoute,
    OrgSlugunauthenticatedRegisterRoute: OrgSlugunauthenticatedRegisterRoute,
  }

const OrgSlugunauthenticatedRouteRouteWithChildren =
  OrgSlugunauthenticatedRouteRoute._addFileChildren(
    OrgSlugunauthenticatedRouteRouteChildren,
  )

interface OrgSlugRouteChildren {
  OrgSlugauthenticatedRouteRoute: typeof OrgSlugauthenticatedRouteRouteWithChildren
  OrgSlugunauthenticatedRouteRoute: typeof OrgSlugunauthenticatedRouteRouteWithChildren
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugauthenticatedRouteRoute: OrgSlugauthenticatedRouteRouteWithChildren,
  OrgSlugunauthenticatedRouteRoute:
    OrgSlugunauthenticatedRouteRouteWithChildren,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
  OrgSlugRoute: OrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
